################################################################################
# File Name     : run_teco.tcl
# Author        : DT-PI
# Creation Date : 2024-02-25
# Last Modified : 2025-05-23
# Version       : v0.3
# Location      : ${STA_SCRIPt_DIR}/apply_PD_dont_touch.tcl
#-------------------------------------------------------------------------------
# Description   :
# 	This file is an example file. This header is used to track the version and
# 	change history of the file.
#-------------------------------------------------------------------------------
# Change Log    :
# 	v0.1 [2025-02-25] : sjlee
# 		- Initial Version Release
# 	v0.2 [2025-03-19] : sjlee
#       - minmax option is added when gen_fsdf and margin options are moved 
# 	v0.3 [2025-05-23] : jaeeun1115
# 		- Change the condition of sourcing dont touch CNP file (info exists -> file exists)
#-------------------------------------------------------------------------------
# Useage        : source apply_PD_dont_touch.tcl
#       
#################################################################################

set CNP_FILE "${SPEF_DIR}/${ECO_NUM}.PD_DONT_TOUCH_CNP.tcl"
# FILE check
if { [file exists $CNP_FILE ] } {
	source  $CNP_FILE

	set CNP_LIST [ info vars PD_DONT_TOUCH_*] 
	# Result> PD_DONT_TOUCH_NET  PD_DONT_TOUCH_PIN PD_DONT_TOUCH_CELL
	foreach CNP $CNP_LIST {
		set fname "./${ECO_NUM}.${CNP}.log"
	 	set FO    [open $fname w]
	 	set TOTAL [llength [set $CNP]]
	 	set PASS 0
	 	set FAIL 0

		foreach itr [set $CNP] {
			# CMD setting
			      if { [string match "*CELL*" $CNP] } {set cmd "set_dont_touch \[get_cells  $itr\] true"
			} elseif { [string match "*NET*"  $CNP] } {set cmd "set_dont_touch \[get_nets   $itr\] true"
			} elseif { [string match "*PIN*"  $CNP] } {set cmd "set_dont_touch \[get_pins   $itr\] true"
			} else   {
				echo "Error_ADF: There's no dont_touch setting file generated by PD"
				echo "Error_ADF: Check the file with PD"
			}
			set result [eval $cmd]
			puts $FO "$result : $cmd"
			if { ${result} } {
				incr PASS
			} else {
				incr FAIL
			}
		}
		puts $FO "# -------------------------------------------------------------------"
		puts $FO "# TOTAL CMD : $TOTAL"
		puts $FO "# PASS  CMD : $PASS"
		puts $FO "# FAIL  CMD : $FAIL"
		puts $FO "# -------------------------------------------------------------------"

		puts "${CNP} Summary" 
		puts "# -------------------------------------------------------------------"
		puts "# TOTAL CMD : $TOTAL"
		puts "# PASS  CMD : $PASS"
		puts "# FAIL  CMD : $FAIL"
		puts "# -------------------------------------------------------------------"
		puts ""
		unset TOTAL
		unset PASS
		unset FAIL
		close $FO
	}
} else {
	puts "Error_ADF: could not found file --> $CNP_FILE"
	puts "Error_ADF: If you do not have a dont_touch CNP file, please contact PD Eng'r."
	puts "Error_ADF: If you do not have a dont_touch CNP file, please contact PD Eng'r."
	puts "Error_ADF: If you do not have a dont_touch CNP file, please contact PD Eng'r."
	puts "Error_ADF: If you do not have a dont_touch CNP file, please contact PD Eng'r."
	exec touch :ERROR:NOT_FOUND_CNP_FILE
}
