################################################################################
# File Name     : compare_max_transition_lib_vs_constraint.tcl
# Author        : DT-PI
# Last Modified : 2025-09-23
# Version       : v1.0
# Location      : execute file
#-------------------------------------------------------------------------------
# Description   :
# 	The Library Max Transition value and the User Constraint Max Transition value are compared,
# 	and the worst value is applied.
#-------------------------------------------------------------------------------
# Change Log    :
# 	v0.1 [2024-11-04] : iskim1001
#       - Initial Version Release
# 	v0.2 [2024-11-04] : iskim1001
#       - Added case where Clock's Period or Library value does not exist.
# 	v0.3 [2024-12-18] : iskim1001
#       - Modify Line : Request Q-SoC Project : http://redmine.adtek.co.kr:21380/issues/5088#note-45
#			Before : #set AllRegCellPin_DATA   [get_pins      -quiet -of_objects $AllRegCell -filter "is_clock_pin==false"]
#			After  : #set AllRegCellPin_DATA   [get_pins      -quiet -of_objects $AllRegCell -filter "is_clock_pin==false && is_clock_network == false"  ]
# 	v0.4 [2025-01-15] : iskim1001
# 		- Modify Line :
#			Before : set LibPin_MaxTran_CLK_Minimum   [lindex [lsort -unique -real $LibPin_MaxTran_CLK   ] 0]
#			After  : set LibPin_MaxTran_CLK_Minimum   [format "%.7f" [::tcl::mathfunc::min {*}$LibPin_MaxTran_CLK   ]  ]
#		- Add Command : Request of sjlee
#			set CellPin_MaxTran_CLK   [get_attribute $AllRegCellPin_CLK  constraining_max_transition]
#			set CellPin_MaxTran_DATA  [get_attribute $AllRegCellPin_DATA constraining_max_transition]
# 	v0.5 [2025-01-20] : jaeeun1115
# 	    - set LibPin_MaxTran_CLK_Minimum   [lindex [lsort -unique -real $LibPin_MaxTran_CLK   ] 0]
# 	v0.6 [2025-02-02] : jaeeun1115
# 	    - Add condition to ignore null values for reporting
# 	v0.7 [2025-03-13] : jaeeun1115
# 	    - Delete set_max_transition -data_path
# 	v0.8 [2025-05-10] : iskim1001
# 		- Variable Modify :
# 			Before : set AllRegCellPin_CLK    [get_pins      -quiet -of_objects $AllRegCell -filter "is_clock_pin==true"]
# 			 After : set AllRegCellPin_CLK    [get_pins      -quiet -of_objects $AllRegCell -filter "is_clock_pin==true && cell.is_black_box==false "]
# 	v0.9 [2025-05-14] : jaeeun1115
# 		- Modify input sdc name
# 	v1.0 [2025-09-23] : jaeeun1115
# 		- Exclude ETM reference cell
#
#################################################################################

set COMPARE_DEBUG "0"

set scr_version     "v0.8 (2025.05.10)"
file mkdir report

set FO_SDC     [open ${OUTPUT_DIR}/${DESIGN}.${MODE}-${typ_volt}.${CORNER}.sdc "a" ]

if { $COMPARE_DEBUG } {
	set FA_RPT [open ./report/compare_max_tran_CLK.rpt             "w" ]
	set FB_RPT [open ./report/compare_max_tran_DATA.rpt            "w" ]
}


set ClkList [get_object_name [get_clocks * -filter "defined(sources)"] ]
puts $FO_SDC "\n"
puts $FO_SDC "###############################################################################"
puts $FO_SDC "# ** Note ** Max Transition Override "
puts $FO_SDC "# The set_max_transition command below was generated by"
puts $FO_SDC "# \${COMMON_TCL_PT}/compare_max_transition_lib_vs_constraint.tcl script."
if { [info exist PRatio_CLK  ] } {
	set PRatio_CLK  $PRatio_CLK
} else {
	set PRatio_CLK 0.1
	puts $FO_SDC "# The PRatio_CLK variable is not set, so the default value is assigned. (Default is $PRatio_CLK )"
}
if { [info exist PRatio_DATA ] } {
	set PRatio_DATA $PRatio_DATA
} else {
	set PRatio_DATA 0.4
	puts $FO_SDC "# The PRatio_DATA variable is not set, so the default value is assigned. (Default is $PRatio_DATA )"
}
puts $FO_SDC "###############################################################################\n"

puts $FO_SDC "# The default value of Clock Max Transition is 10% of the Clock Period. ( Current Value : $PRatio_CLK )"
puts $FO_SDC "# The default value of Data Max Transition is 40% of the Clock Period.  ( Current value : $PRatio_DATA )"
puts $FO_SDC "# If the Library Max Transition Value is Worst than the User Constarint Max Transition Value, "
puts $FO_SDC "# the Max Transition Value will be replaced by the Library value. "
puts $FO_SDC "# In the opposite case, it will not be replaced.\n"



if { $COMPARE_DEBUG } {
	###########################################################################
	# Display header
	###########################################################################
	puts $FA_RPT "#*************************************************************"
	puts $FA_RPT "# Report         : comare_max_transition_lib_vs_constraint CLK "
	puts $FA_RPT "# Design         : ${DESIGN}                                   "
	puts $FA_RPT "# Version        : $sh_product_version                         "
	puts $FA_RPT "# Date           : [exec date]                                 "
	puts $FA_RPT "# Scr Version    : $scr_version                                "
	puts $FA_RPT "#*************************************************************"
	puts $FA_RPT ""
	puts $FA_RPT "##########################################"
	puts $FA_RPT "# CLOCK : <CLOCK_NAME>                    "
	puts $FA_RPT "##########################################"
	puts $FA_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" "LibMaxTran" "InstPinTran" "LibPin" "InstPin"]"

	puts $FB_RPT "**************************************************************"
	puts $FB_RPT "# Report         : comare_max_transition_lib_vs_constraint DATA "
	puts $FB_RPT "# Design         : ${DESIGN}                                    "
	puts $FB_RPT "# Version        : $sh_product_version                          "
	puts $FB_RPT "# Date           : [exec date]                                  "
	puts $FB_RPT "# Scr Version    : $scr_version                                 "
	puts $FB_RPT "**************************************************************"
	puts $FB_RPT ""
	puts $FB_RPT "##########################################"
	puts $FB_RPT "# CLOCK : <CLOCK_NAME>                    "
	puts $FB_RPT "##########################################"
	puts $FB_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" "LibMaxTran" "InstPinTran" "LibPin" "InstPin"]"
}




foreach CLK $ClkList {
	;# Signoff Mttv Clk & Data Value
	set CLK_period    [get_attribute -q  [get_clocks $CLK] period]
	if { $CLK_period == "" } {
		puts $FO_SDC "#$CLK --> Skip because Period is not defined."
	} else {
		puts "Information_ADF: Create compare_max_tran ( $CLK ) START"
		set SoffMttv_CLK  [format "%.7f" [expr $CLK_period * $PRatio_CLK ] ]
		set SoffMttv_DATA [format "%.7f" [expr $CLK_period * $PRatio_DATA] ]

        if { $HIER_DESIGN != "" && ![regexp -nocase "NONE" $HIER_DESIGN] } {
            foreach refname $READ_DB_LISTS {
                if {[regexp {(,ETM,)} $refname]} {
                    set ETM_DESIGN [lindex [split $refname ,] 0]
                    set ETM_CELL   [get_object_name [get_cells -h -f "ref_name =~ $ETM_DESIGN"]]
                    lappend ALL_ETM_CELL $ETM_CELL
                }
            }
            if { [info exist ALL_ETM_CELL] } {
                puts "\nETM_block full_name: "
                foreach etm_cell $ALL_ETM_CELL {
                    puts "$etm_cell"
                }
                puts ""
            }
        }

        if { [info exist ALL_ETM_CELL] } {
            set AllReg         [remove_from_collection [all_registers -clock $CLK] $ALL_ETM_CELL]
        } else {
            set AllReg         [all_registers -clock $CLK]
        }
		set AllRegCell         [get_cells     -quiet $AllReg  -filter "ref_name!~ *ICG* || is_integrated_clock_gating_cell==false && is_memory_cell==false && full_name !~ *LOCKUP*" ]

		set AllRegCellPin_CLK  [get_pins -quiet -of_objects $AllRegCell -filter     "is_clock_pin==true && \
		                                                                        cell.is_black_box==false"]



		set AllRegCellPin_DATA   [get_pins      -quiet -of_objects $AllRegCell -filter "is_clock_pin==false && is_clock_network == false"  ]
		set LibPin_CLK           [get_attribute $AllRegCellPin_CLK  lib_pin]
		set LibPin_DATA          [get_attribute $AllRegCellPin_DATA lib_pin]

		set CellPin_MaxTran_CLK   [get_attribute $AllRegCellPin_CLK  max_transition]
		set CellPin_MaxTran_DATA  [get_attribute $AllRegCellPin_DATA max_transition]
		set LibPin_MaxTran_CLK    [get_attribute -q $LibPin_CLK  max_transition]
		set LibPin_MaxTran_DATA   [get_attribute -q $LibPin_DATA max_transition]
 		set LibPin_MaxTran_CLK_Minimum   [lindex [lsort -unique -real $LibPin_MaxTran_CLK   ] 0]
 		set LibPin_MaxTran_DATA_Minimum  [lindex [lsort -unique -real $LibPin_MaxTran_DATA  ] 0]
 		set CellPin_MaxTran_CLK_Minimum  [lindex [lsort -unique -real $CellPin_MaxTran_CLK  ] 0]
 		set CellPin_MaxTran_DATA_Minimum [lindex [lsort -unique -real $CellPin_MaxTran_DATA ] 0]
#		set LibPin_MaxTran_CLK_Minimum   [format "%.7f" [::tcl::mathfunc::min {*}$LibPin_MaxTran_CLK   ]  ]
#		set LibPin_MaxTran_DATA_Minimum  [format "%.7f" [::tcl::mathfunc::min {*}$LibPin_MaxTran_DATA  ]  ]
#		set CellPin_MaxTran_CLK_Minimum  [format "%.7f" [::tcl::mathfunc::min {*}$CellPin_MaxTran_CLK  ]  ]
#		set CellPin_MaxTran_DATA_Minimum [format "%.7f" [::tcl::mathfunc::min {*}$CellPin_MaxTran_DATA ]  ]

		# ::tcl::mathfunc::min {*}$AA
		# URL : https://solvnetplus.synopsys.com/s/article/Finding-the-Minimum-Maximum-Sum-or-Average-of-a-List-of-Values-in-Tcl-1576135581368
		;# Header Display
		puts $FO_SDC "################################################################################"
		puts $FO_SDC "# Clock Name ( Period ) : $CLK ( $CLK_period )"
		puts $FO_SDC "################################################################################"

		;# CLK MTTV Display
		puts $FO_SDC "[format "# Sign-off Constraint Max Transition CLK ( %-9s )" $SoffMttv_CLK                ]"
		puts $FO_SDC "[format "# Library  Constraint Max Transition CLK ( %-9s )" $LibPin_MaxTran_CLK_Minimum  ]"
		puts $FO_SDC "[format "# CellPin  Constraint Max Transition CLK ( %-9s )" $CellPin_MaxTran_CLK_Minimum ]"
		set MinList_temp [list  $SoffMttv_CLK $LibPin_MaxTran_CLK_Minimum $CellPin_MaxTran_CLK_Minimum  ]
        foreach item $MinList_temp {
            if {$item == ""} {
                continue
            } else {
                lappend MinList $item
            }
        }
		set Value   [lindex $MinList 0]
		foreach item $MinList  {
			if {$item < $Value} {
				set Value $item
			}
		}
        unset MinList
		puts $FO_SDC "set_max_transition -clock_path  $Value \[get_clocks $CLK \] \n "


		;# DATA MTTV Display
		#puts $FO_SDC "[format "# Sign-off Constraint Max Transition DATA ( %-9s )" $SoffMttv_DATA                ]"
		#puts $FO_SDC "[format "# Library  Constraint Max Transition DATA ( %-9s )" $LibPin_MaxTran_DATA_Minimum  ]"
		#puts $FO_SDC "[format "# CellPin  Constraint Max Transition DATA ( %-9s )" $CellPin_MaxTran_DATA_Minimum ]"
		set MinList_temp [list  $SoffMttv_DATA $LibPin_MaxTran_DATA_Minimum $CellPin_MaxTran_DATA_Minimum  ]
        foreach item $MinList_temp {
            if {$item == ""} {
                continue
            } else {
                lappend MinList $item
            }
        }
		set Value   [lindex $MinList 0]
		foreach item $MinList  {
			if {$item < $Value} {
				set Value $item
			}
		}
        unset MinList
		#puts $FO_SDC "set_max_transition -data_path  $Value \[get_clocks $CLK \] \n\n "


		# Debug Display
			if { $COMPARE_DEBUG } {
				puts $FA_RPT ""
				puts $FA_RPT "##########################################"
				puts $FA_RPT "# CLOCK : $CLK                            "
				puts $FA_RPT "##########################################"
				puts $FA_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" "LibMaxTran" "InstPinTran" "LibPin" "InstPin"]"

				puts $FB_RPT ""
				puts $FB_RPT "##########################################"
				puts $FB_RPT "# CLOCK : $CLK                            "
				puts $FB_RPT "##########################################"
				puts $FB_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" "LibMaxTran" "InstPinTran" "LibPin" "InstPin"]"

				foreach_in_collection AA $AllRegCellPin_CLK {
					set InstPin     [get_object_name $AA]
					set LibPin      [get_object_name  [get_attribute [get_pins $InstPin] lib_pin] ]
					set InstPinTran [get_attribute -q [get_pins $InstPin] max_transition]
					set LibPinTran  [get_attribute -q [get_lib_pin $LibPin]  max_transition]
					if { $LibPinTran  == "" } { set LibPinTran  "Not_Define"				}
					if { $InstPinTran == "" } { set InstPinTran "Not_Define"				}
					puts $FA_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" $LibPinTran $InstPinTran $LibPin $InstPin]"
				}

				foreach_in_collection AA $AllRegCellPin_DATA {
					set InstPin     [get_object_name $AA]
					set LibPin      [get_object_name  [get_attribute [get_pins $InstPin] lib_pin] ]
					set InstPinTran [get_attribute -q [get_pins $InstPin] max_transition]
					set LibPinTran  [get_attribute -q [get_lib_pin $LibPin]  max_transition]
					if { $LibPinTran  == "" } { set LibPinTran  "Not_Define"				}
					if { $InstPinTran == "" } { set InstPinTran "Not_Define"				}
					puts $FB_RPT "[format "#( %-12s : %-12s ) : %-10s --> %s" $LibPinTran $InstPinTran $LibPin $InstPin]"
				}
			}
			puts "Information_ADF: Create compare_max_tran ( $CLK ) END"
		}
	}
close $FO_SDC

if { $COMPARE_DEBUG } {
	close $FA_RPT
	close $FB_RPT
}
