# ------------------------------------------------#
# Description : Makefile for Synthesis
# ------------------------------------------------#
# Define current design
# ------------------------------------------------#
DESIGN           = AUTO_DETECT

#------------------------------------------------#
# link dk list  " prim mem ip "
#------------------------------------------------#
ABS_READS       = "prim mem ip"

#------------------------------------------------#
# Choose whetner to quit
#------------------------------------------------#
QUIT_ON_FINISH  = 0

#------------------------------------------------#
# Default
#------------------------------------------------#
.PHONY : default
default : run
include $(COMMON_IMPL_DIR)/common_fc_syn/common_makefile
